### ISSUE TITLE
Direnv shadows vars for quickenv

### ISSUE THREAD

**Issue by verglasz** [untitaker/quickenv#13]
At first I thought it was a problem with symlinks, because of how I observed it (and even reproduced it) but evidently it was probably due to some coincidence.
Not sure if intentional or not, but at the very least it's surprising to me:
```
echo "A=$A"
# A=
echo "export A=1" > .envrc
direnv allow
#direnv: loading ./.envrc
#direnv: export +A
quickenv reload
quickenv vars
# DIRENV_IN_ENVRC=1
echo "A=$A"
# A=1
```
I was thinking of using quickenv for example to create an .env file (or just provide one with `<(quickenv vars)` to other programs that rely on it for various configurations, but this means that I can't really use it for that purpose.

**Comment by untitaker** [comment]
Quickenv is a replacement for the default direnv shell hooks. Why do you want to run both on your machine?

**Comment by verglasz** [comment]
In general I find direnv convenient but for some .envrcs I like to have the option of only running them as needed with quickenv; more specifically I ran into this because as I mentioned, direnv lacks a good way to export the var list, and it's sometimes convenient to pass `--env-file <(quickenv vars)` to some programs (eg, it's a lot quicker and less repetitive than specifying every env var to be forwarded with `docker compose`), but this didn't work on a direnv-trusted workspace.

**Comment by untitaker** [comment]
you can do `direnv exec /usr/bin/env` and it should kinda work. alternatively you can use the private API used by the shell hook `direnv export bash`, and grep the output so that it works for you. but i am still not sure how to make simultaneous use of quickenv and direnv possible in a way that makes any sense

**Comment by untitaker** [comment]
Let me know if you have any other questions, I don't think you need quickenv for your purposes though.
